INSERT INTO payment VALUES ('online',SYSTIMESTAMP,1,1);
INSERT INTO payment VALUES ('online',SYSTIMESTAMP,2,2);
INSERT INTO payment VALUES ('offline',SYSTIMESTAMP,3,3);
INSERT INTO payment VALUES ('online',SYSTIMESTAMP,4,4);
INSERT INTO payment VALUES ('online',SYSTIMESTAMP,5,5);
INSERT INTO payment VALUES ('offline',SYSTIMESTAMP,6,6);
INSERT INTO payment VALUES ('online',SYSTIMESTAMP,7,7);
INSERT INTO payment VALUES ('online',SYSTIMESTAMP,8,8);
INSERT INTO payment VALUES ('offline',SYSTIMESTAMP,9,9);
INSERT INTO payment VALUES ('online',SYSTIMESTAMP,10,10);

